### ISSUE TITLE
Output of TealData should be tdata

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.data#121]
Should be done with https://github.com/insightsengineering/teal/issues/783

We are aiming to make tdata the universal data object in the teal framework. This issue is to update the `teal.data` package so that the data coming out of it for `teal::init` is of type `tdata`

1) The class definition of tdata should be moved out of teal and into here
2) TealData$pull() should output a `tdata` object
3) For non DDL data a tdata object should be created from the datasets
4) tdata should have CodeClass

In the future #102 along with https://github.com/insightsengineering/teal/issues/764#issuecomment-1318403191 will simplify the teal.data api and push the use of tdata further into teal.data but that is not this issue

**Comment by gogonzo** [comment]
Probably we need to store CodeClass in tdata as we need a way to subset code for selected datasets. `code` could be an expression only if we decide to not subset the code or if we figure out [this](https://github.com/insightsengineering/teal.data/issues/37)
