### ISSUE TITLE
Include ADQLQC in the list of supported cdisc_datasets

### ISSUE THREAD

**Issue by sob2021** [insightsengineering/teal.data#122]
Hello,
ADQLQC (EORTC QLQ-C30 V3 Analysis Dataset) is an ADAM dataset available in the GDSR.
Please can you add this to list of supported cdisc datasets.

Thank you.

@shajoezhu 

```
> get_cdisc_keys("ADQLQC")
Error in get_cdisc_keys("ADQLQC") : There is no dataset called: ADQLQC 
  List of supported cdisc_datasets:
   ADSL, ADAE, ADEG, ADTTE, ADAETTE, ADCM, ADEX, ADLB, ADMH, ADQS, ADRS, ADSAFTTE, ADVS, ADDV, ADSUB, ADHY

```

**Comment by donyunardi** [comment]
Hi @sob2021, it's been a while, hope you're doing well. =)

`get_cdisc_keys` is pulling the information from this file:
https://github.com/insightsengineering/teal.data/blob/main/inst/cdisc_datasets/cdisc_datasets.yaml

Adding `ADQLQC` is just a matter of adding the information to the yaml file.
Are you currently developing a module that's using this dataset?

@lcd2yyz 
Is this dataset something that we'd like to support?

@Polkas 
It's seems like a simple update. Is there any blindspot that I'm missing?

**Comment by sob2021** [comment]
Hello @donyunardi 
Thank you so much for looking into this, I'm OK thank you. Hope you are doing well too.
I'm currently working with PCOR in developing a package for psychometric analysis. We are developing a module using the ADQLQC dataset.

**Comment by shajoezhu** [comment]
Thanks a lot @donyunardi , @sob2021 can you please also provide the headers as well. Thanks

**Comment by sob2021** [comment]
Hi  @shajoezhu 
Sure, please see below: 

ADQLQC:
  primary: ["STUDYID", "USUBJID", "PARCAT1N", "PARAMCD", "BASETYPE",  "AVISITN", "ATPTN" "ADTM" "QSSEQ"]
  foreign: ["STUDYID", "USUBJID"]
  parent: "ADSL"

Thank you.

**Comment by nikolas-burkoff** [comment]
So you can pass in the keys explicitly for a dataset whose keys aren't available in get_cdisc_keys`:



![Image](https://user-images.githubusercontent.com/15201933/207870912-68333106-30c5-4ee9-ab78-0ede6c4a742a.png)

**Comment by shajoezhu** [comment]
thanks a lot Nik. `ADQLQC` is also listed in our GDSR, and it is requested from our PICO users. 

I will recommend and suggest study teams to add keys explicitly in the future.
