### ISSUE TITLE
Include ADCSSRS and ADEQ5D5L in the list of supported cdisc_datasets

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/teal.data#129]
todo

carry out changes similar to https://github.com/insightsengineering/teal.data/pull/127

ADCSSRS keys: 
STUDYID  USUBJID	PARAMCD	BASETYPE	AVISITN	DTYPE	ADTM	ADTM	

ADEQ5D5L keys:
STUDYID  USUBJID	PARCAT1N	PARAMCD	BASETYPE	AVISITN	ATPTN	ADTM	QSSEQ

**Comment by edelarua** [comment]
> ADCSSRS keys: STUDYID USUBJID PARAMCD BASETYPE AVISITN DTYPE ADTM ADTM

@shajoezhu ADTM is listed twice here. Is that supposed to be a different variable or just accidentally listed twice?
