### ISSUE TITLE
[Bug]: GRAN test failure

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.data#135]
### What happened?

```
* checking tests ...
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > pkg_name <- "teal.data"
  > library(pkg_name, character.only = TRUE)
  Loading required package: shiny
  > testthat::test_check(pkg_name)
  [ FAIL 1 | WARN 1 | SKIP 0 | PASS 1017 ]
  
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error ('test-JoinKeys.R:581'): JoinKeys$get_parent returns NULL when dataset is not found or not passed ──
  
  Error in `private$parents[[dataname]]`: missing subscript
  Backtrace:
      ▆
   1. ├─testthat::expect_null(jk$get_parent()) at test-JoinKeys.R:581:2
   2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
   3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
   4. └─jk$get_parent()
  
  [ FAIL 1 | WARN 1 | SKIP 0 | PASS 1017 ]
  Error: Test failures
  Execution halted
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
The `get_parent` method requires `dataname` argument:
https://github.com/insightsengineering/teal.data/blob/46ede36a83b7297b0519b8b905fbcdc151c39477/R/JoinKeys.R#L197-L199

In the test, there is no argument passed:
https://github.com/insightsengineering/teal.data/blob/46ede36a83b7297b0519b8b905fbcdc151c39477/tests/testthat/test-JoinKeys.R#L581

This is when we got different behavior in our CICD and GRAN. In our pipeline, it returns NULL (not sure why) but in GRAN, it's error out.

I'll call it explicitly in the code to return NULL when the method is being called without argument.
