### ISSUE TITLE
Refactor DataAbstract to use the new methods for joining and splitting keys

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.data#14]
With the merging of this issue: https://github.com/insightsengineering/teal/pull/177

we now have the tools to merge and split join keys in DataAbstract. Objective:
* track down and eliminate all the occurrences of splitting and joining keys done "by hand" and reinstate the logic by using the new shiny toys from JoinKeys

**Comment by gogonzo** [comment]
Not relevant anymore. New implementation of teal_data, teal_data_module and join_keys already on main
