### ISSUE TITLE
Decouple `scda` from teal.data

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.data#145]
### Summary
In order to release teal.data, it is necessary to separate it from scda since scda will not be available on CRAN. Currently, scda_data_connector creates a dependency between teal.data and scda. 

One suggestion is to develop a specialized extension of teal.data specifically for scda, named `teal.data.scda`.

### Acceptance Criteria
* Remove `scda_dataset_connector` function
* Discuss if we need to move the function to extension package
* `scda` is not a dependency of `teal.data`.

**Comment by donyunardi** [comment]
We may need `scda` for teal.data for now due to `scda_dataset_connector` function.

**Comment by kartikeyakirar** [comment]
@gogonzo, Do we need to have a specialized extension of teal.data called teal.data.scda at this moment? Considering that we have already decoupled most of the packages from scda, I'm unsure if we currently need this extension.

**Comment by gogonzo** [comment]
@kartikeyakirar we are going to refactor teal.data and having teal.data.scda would be unnecessary complication. Let's remove all `scda` relationships.

**Comment by m7pr** [comment]
Hey guys, I think this should be opened, becuase #153 is not merged
