### ISSUE TITLE
Deprecate get_code.default

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#173]
This `get_code` method is a very old function which can read the preprocessing (everything before teal::init) to obtain code needed to reproduce the data. Function is used for example in [longitudinal example app](https://github.com/insightsengineering/teal.gallery/blob/6e3e42420aec2090bb469b5403c33830632c35d8/longitudinal/app.R#L422) to avoid writing code to `cdisc_data(code)` argument. This function has a very limited functionality and albo collides with `get_code` method for `qenv` and `teal_data`. We should have only one `get_code` method in the whole framework.

Function should be deprecated now, and removed with old TealData related functions after next release.

**Comment by m7pr** [comment]
Hey, once this is removed please add 

```r
@name get_code
@rdname get_code
```

to `R/teal_data-get_code.R` file.

Thanks
