### ISSUE TITLE
Write a new vignette about `teal_data`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#174]
Since TealData is deprecated, we should no longer teach in the vignettes about this class. So we have (at least) two altnernative solutions:
- remove vignettes describing all (unwanted) ways of specifying data
- state in the old vignettes that their content is deprecated

There should be new vignettes:
- [x] `teal_data` class and it's methods and idea behind @gogonzo 
- [x] Reproducibility check
- [x] https://github.com/insightsengineering/teal.data/issues/202
- [x] using `teal_data` in teal application (this should be in `teal`)
- [x] how to migrate from `TealData` to `teal_data` and from `tdata` to `teal_data` @vedhav

**Comment by chlebowa** [comment]
How about flag the old vignettes as archival and have a mention in the new one that other ways existed in the past?

**Comment by vedhav** [comment]
I'm leaning towards not showing vignettes about the old stuff. As a user, I will be overwhelmed with a lot of deprecated stuff in the vignettes. Alternatively, it will be nice to place all the depreciated vignettes in just one navigation selection, my worry is that this will still make it available for search and easily mislead someone.

**Comment by m7pr** [comment]
If we do support depracated functionality I would leave vignettes with a warning that they refer to the deprecated functionality. Once the functionality is removed I would opt for vignettes removal.  The same way we keep manual pages for deprecated stuff.

**Comment by kartikeyakirar** [comment]
Keep old vignettes might be helpful if someone migrating from old to new , currently, we still support some of the old functionality, so it might be beneficial to retain the old vignettes with a disclaimer or warning.

**Comment by gogonzo** [comment]
> Keeping old vignettes might be helpful if someone migrating from old to new 

So we need extra vignette - "Migrate from `TealData` to `teal_data`"

**Comment by m7pr** [comment]
> So we need extra vignette - "Migrate from TealData to teal_data"
yeah, that would be the best!
