### ISSUE TITLE
[Feature request] Introduce validate method for `teal_data`

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#182]
0. Add `@valid` slot to the `teal_data` class
1. `teal_data(` object when initialized empty should have `@valid = TRUE` by default
2. `teal_data` object when initialized not empty (with iniital data or code) should have `@valid = FALSE`
3. Such object could be provided to teal without consequences.
4. `get_code` method should add extra message on top `warning("code is not valid")` - please rephrase
5. To change `@valid` to `TRUE` can be done only by using `validate()` method. `validate()` method should run the code in new.env and compare result with `@env`. If not `identical` then `stop`. 
6. Find the better name for `validate()` function as it is already in `shiny` (to avoid masking)

Reproducible application code could look like this:

```r
data <- teal_data(
  IRIS = iris, 
  MTCARS = mtcars, 
  code = quote({
    IRIS <- iris 
    MTCARS <- mtcars
  })
) # @valid is FALSE


data <- data |> validate() # @valid will be TRUE or error
```

**Comment by m7pr** [comment]
closed with https://github.com/insightsengineering/teal.data/pull/188
