### ISSUE TITLE
[Feature Request]: Set default parent

### ISSUE THREAD

**Issue by averissimo** [insightsengineering/teal.data#203]
### Problem:

When creating a new `join_keys` object with foreign keys it requires an external call to define parents

``` r
library(teal.data)
join_keys(
  join_key("A", keys = "id_a"),
  join_key("B", keys = "id_b"),
  join_key("A", "B", keys = c(id_b = "id_a"))
) |> parents()
#> list()
```

### Benefit

Single calls create valid/complete `join_keys` without any extra manipulation.

### Solution A: assume directonality on `join_key()` call 

- `join_key("A", "B", keys = c(id_b = "id_a"))` assumes first/second dataset to be parent
  - add parameter paremeter to disable this assumption
  - alternative, don't assume and add parameter to define parent
    - `join_key("A", "B", keys = c(id_b = "id_a"), parent = "A")`

### Solution B: add parent argument to constructor

Only valid for constructor

```r
data_1 <- data.frame(X = factor(1:10), Y = 21:30, Z = 1:10)
data_2 <- data.frame(W = factor(10:1), V = factor(5:14), M = rep(1:5, 2))

data <- teal_data(
  D1 = data_1,
  D2 = data_2,
  join_keys = join_keys(
    join_key("D1", "D2", c("X" = "W")),
    parents = list(D2 = "D1")
  )
)
```

<details>

<summary>Draft implementation of solution 2</summary>

```diff
diff --git a/R/join_keys.R b/R/join_keys.R
index 8b962c07..7cf36105 100644
--- a/R/join_keys.R
+++ b/R/join_keys.R
@@ -62,7 +62,16 @@ join_keys <- function(...) {
 #' @order 1
 #' @export
 join_keys.default <- function(...) {
-  c(new_join_keys(), ...)
+  x <- rlang::list2(...)
+  new_parents <- list()
+  if (!is.null(names(x)) && "parents" %in% names(x)) {
+    new_parents <- x[["parents"]]
+    checkmate::assert_list(new_parents, names = "named", types = "character", .var.name = "parents")
+    x <- x[names(x) != "parents"]
+  }
+  new_jk <- do.call(c, append(list(new_join_keys()), x))
+  parents(new_jk) <- new_parents
+  new_jk
 }
```

</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
I propose to automatically set `child->parent` relationships when foreign keys are set. This means that every foreign key pair would have child->parent relationship. How api would look like:

- `parents(join_keys)` will always return a list
- `parents(join_keys) <- ` will be tricky as provided list will have to match foreign join keys (ALWAYS)
- `join[child1, child2]` implicit join_keys will be still available.

There should be no consequences in our apps as they use cdisc join keys with default parents.

**Comment by averissimo** [comment]
Agree!

> parents(join_keys) <- will be tricky as provided list will have to match foreign join keys (ALWAYS)

It already protects against setting parents that don't have foreign keys :-)

Q: Is there any additional scenario that we should look into _(as in removing parents by omission)_

``` r
library(teal.data)
#> Loading required package: shiny
jk <- teal.data::join_keys(
  join_key("ds1", keys = "aa"),
  join_key("ds2", keys = "bb")
)
parents(jk) <- list(ds2 = "ds1")
#> Error in assert_parent_child(x): No join keys from ds2 to its parent (ds1) and vice versa
```

**Comment by gogonzo** [comment]
> It already protects against setting parents that don't have foreign keys :-)

Right, this we have covered.

> Q: Is there any additional scenario that we should look into (as in removing parents by omission)

I don't expect any other cases. Expected conditions on parents:
- all foreign key pairs should have child-parent
- all child-parent should have foreign keys
- child-parent graph should be acyclic

In `teal` we use parents in following cases:
- If certain module uses for example "ADTTE" then its datasets are extended to c(<recursive ancestors of adtte>, "ADTTE") 
- In filter panel changes in one dataset filters updating (reactively) on changes in ancestors

**Comment by gogonzo** [comment]
> Wasn't it

Let's give some freedom to an assignee and a reviewer
