### ISSUE TITLE
message about teal_data not defined when load_all() is performed

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.data#221]
When loading the teal.data package using `devtools::load_all()`, I see a message indicating that the `teal_data` class is not defined. However, this message does not appear when loading the package using `library()`.

![image](https://github.com/insightsengineering/teal.data/assets/8597300/203425ce-d00c-4a5d-94e8-abaec7d5a22e)

The message arises because, during the `load_all()` process, R loads the R files in alphabetical order. The file containing the definition for the `teal_data` class is named `teal_data.R`, while the file for `datanames` is named `datanames.R`.

Consequently, `datanames.R` gets loaded before `teal_data.R`, leading to the message indicating that `teal_data` is not defined.
We can solve this by renaming the files to ensure the right order when loading.

For example, the message is no longer appear if I rename the file from `datanames.R` to `zz-datanames.R`.

![image](https://github.com/insightsengineering/teal.data/assets/8597300/840b0729-19ed-4c96-9cb4-a682caa2823f)

Should we consider renaming to make sure a proper loading sequence?

**Comment by donyunardi** [comment]
@insightsengineering/nest-core-dev 
How does everyone feels about changing `datanames.R` to `teal_data-datanames.R` to make it consistent with other methods (`teal_data-get_code.R` and `teal_data-show.R`)?

![image](https://github.com/insightsengineering/teal.data/assets/8597300/66c05262-01fe-4c8e-a931-e85796bfcca7)

**Comment by chlebowa** [comment]
This should be solved by putting `@include teal_data.R` in `datanames.R` but somehow isn't.
Let's change the file name :+1:

**Comment by m7pr** [comment]
I was thinking teal_data-datanames.R as Dony mentioned would be the most consistent with other files
