### ISSUE TITLE
Should we returned non-deparsed code of length 1 for `teal::data.get_code.teal_data`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.data#224]
### What is your question?

Hey, currently we return different length of output depending on it's deparsed or not in `get_code`

```r
library(teal.data)
tdata1 <- teal_data()
tdata1 <- within(tdata1, {
  a <- 1
  b <- a^5
  c <- list(x = 2)
})

length(get_code(tdata1, deparse = FALSE))
# > [1] 3
length(get_code(tdata1, deparse = TRUE))
# > [1] 1
```

This is inconsistent with `teal.code::get_code` for `qenv` objects, where we paste final expression so it always has length 1

https://github.com/insightsengineering/teal.code/blob/a017cec9ec121b96ae1764ceb58fad2907977135/R/qenv-get_code.R#L43

```r
parse(text = paste(c("{", object@code, "}"), collapse = "\n"), keep.source = TRUE)
```

```r
library(teal.code)
qe <- qenv() |> within(i <- iris) |> within(m <- mtcars)
get_code(qe, deparse = FALSE)
# > expression({
# > i <- iris
# > m <- mtcars
# > })
length(get_code(qe, deparse = FALSE))
# > [1] 1
```

Such behavior in `teal.code` was introduced during https://github.com/insightsengineering/teal.code/pull/176
I believe we should introduce the same in `teal.data`

**Comment by chlebowa** [comment]
Good point, we should absolutely keep things consistent, :+1:

**Comment by m7pr** [comment]
Coolio @chlebowa ! Thanks, any chance you can skim the PR? https://github.com/insightsengineering/teal.data/pull/225
