### ISSUE TITLE
CallableFunction$set_args fails when the function is an S4 method "mean"

### ISSUE THREAD

**Issue by kpagacz** [insightsengineering/teal.data#25]
A small example:
```r
library(MultiAssayExperiment)
callable_function(mean) -> r
r$get_call()
r$set_args(list(x = 1:10, na.rm = FALSE))
```
this fails at set_args. Outputs below:
![image](https://user-images.githubusercontent.com/24480246/135638291-6135a289-fc55-4112-a543-59d79c96d804.png)
![image](https://user-images.githubusercontent.com/24480246/135638264-f49f791b-8884-4b77-91a5-592695bda309.png)

**Comment by donyunardi** [comment]
We won't be pursuing this issue. It seems like a minor issue with a unique situation.
