### ISSUE TITLE
[Question]: Should `get_code_dependency()` return usage of the object next to the code needed to create the object?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.data#255]
Currently `get_code_dependency()` was meant to return code needed to recreate the object specified by it's name in `datanames` parameter. Below example returns the code needed to recreate the `z` object, but also lines where `z` is used as the only `SYMBOL` in the call.

```r
code <- c("z <- 5", "head(z)")
tdata <- eval_code(teal_data(), code)
get_code(tdata, datanames = "z")
get_code_dependency(tdata@code, names = "z")
```

```r
[1] "z <- 5\nhead(z)"
[1] "z <- 5"  "head(z)"
```

If we ever decide just to keep code extraction to the point where the object is created and edited (and not used), then the changes need to be provided in `extract_occurrence()`
https://github.com/insightsengineering/teal.data/blob/1249d8d71f249505fd7b8cf04edb53f80916c8ca/R/utils-get_code_dependency.R#L219-L224

So that if there is only just one `"SYMBOL"` and (potentially just one `"SYMBOL_FUNCTION_CALL"`) 
then `extract_occurrence()` should return `c("<-", "SYMBOL_text")` (or `character(0)` - think about it)
instead of `c("SYMBOL_text", "<-", "SYMBOL_FUNCTION_CALL_text")`.

**Comment by chlebowa** [comment]
To me the name of the function, `get_code_dependency`, signifies that its purpose is to return code that the particular `dataname` _depends_ on, i.e. code that creates it, not code that uses it.

> lines where `z` is used as the only `SYMBOL` in the call

This is what I could call "object use", as opposed to "object dependency" or "object ancestry".

From a functional point of view it might make sense to have two separate internal functions to retrieve one or the other, even if `get_code` would be intended to return both.

For context:
When calling `get_code(<teal_data>, datanames = "z")` we expect to obtain a subset of the code in `<teal_data>` that can recreate `z` and the code where `z` is used for end effects (plots, etc.). This is done by having `get_code` call `get_code_dependency`.
The one place we _do_ use `datanames` is in `teal`, when converting `filtered_data` to `teal_data`. `FilteredData` keeps (as attribute) all the code that was passed into `init`. This is preprocessing code and may include multiple datasets. When passing data to modules, we want to only pass the code that pertains to the datasets used in the module, hence we subset the code by the value of the `datanames` argument in the module call. We actually call `teal.data:::get_code_dependency` there, which was probably supposed to be replaced by `get_code`. But there is no object use there, only ancestry, so it doesn't matter if we include object use. 
Then, at the end of modules, when we want code (either in Show R Code or in reports), we no longer have a need for subsetting the code, so we use `get_code`, no `datanames`, we take the whole thing. You can get your plot code for dataset `x` mixed up with your table plot for dataset `y`, true, but that can be avoided by having separate `teal_data`s for plot and for table.

**Comment by m7pr** [comment]
So far we landed with a solution where it only returns the code for object creation and not for calls that uses the object for printing or plotting

**Comment by chlebowa** [comment]
> So far we landed with a solution where it only returns the code for object creation and not for calls that uses the object for printing or plotting

Note: the reproducibility vignette states as much. If we change this, don't forget to update there.

**Comment by m7pr** [comment]
Yup! Duly noted
