### ISSUE TITLE
CRAN comments

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#283]
Comments from CRAN reviewer.

> The Description field is intended to be a (one paragraph) description of
what the package does and why it may be useful. Please add more details
about the package functionality and implemented methods in your
Description text.

>If there are references describing the methods in your package, please
add these in the description field of your DESCRIPTION file in the form
authors (year) <doi:...>
authors (year) <arXiv:...>
authors (year, ISBN:...)
or if those are not available: <https:...>
with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
auto-linking.
(If you want to add a title as well please put it in quotes: "Title")

>You have examples for unexported functions. Please either omit these
examples or export these functions.
Examples for unexported function
   default_cdisc_join_keys() in:
      col_labels.Rd

>Please fix and resubmit.

**Comment by chlebowa** [comment]
The examples were accepted in `teal.code`. Is this because that was not the initial submission? If so, I take it the exmaples will be added back in the next release? Perhaps `0.4.1`?

**Comment by gogonzo** [comment]
It might depend on a reviewer also. 

> perhaps 0.4.1

Yup, let's do this. But Today we can maybe move it to @details for a while - I'm waiting for opinion from CRAN reviewer.

**Comment by chlebowa** [comment]
Do you think they could waive the restriction if we explain that these are dev-oriented examples?

**Comment by averissimo** [comment]
Do you want to pre-emptively prepare that move to `@details` ?

I can do it quickly right now that targets the `release-candidate-v0.4.0` branch

**Comment by gogonzo** [comment]
> Do you want to pre-emptively prepare that move to @details ?
Let's wait for answer from CRAN about this. We can address other comments first and wait for their opinion. I'll do respective changes over the weekend if answer comes too late 👍

**Comment by averissimo** [comment]
I'm curious about the rationale behind allowing documentation, but not examples. I can only think that they don't want to waste resources running these examples given that they have to test 10k+ packages regularly on multiple platforms

Still, it seems like they are promoting poor development practices by preventing better documentation

**Comment by chlebowa** [comment]
Probably those examples wouldn't run if we hadn't done the `getFromNamespace` trick. It makes me think it was an automated process: compare names of functions in examples against names of exported funcitons.

**Comment by averissimo** [comment]
We don't have any references describing the methods on `teal.data` so as far as I can tell there are only 2 actions required for resubmission

1. Change/extend description in `DESCRIPTION` file
    - I'll propose a new one
2. Sort out the `@examples`
    - Waiting for a reply from CRAN and act accordingly

**Comment by m7pr** [comment]
If they don't allow examples in the way we have them today, we can resubmit them in another CRAN release, as the next one does not have a human verification. We can do it even after a day or the first CRAN release.

**Comment by gogonzo** [comment]
> If they don't allow examples in the way we have them today, we can resubmit them in another CRAN release, as the next one does not have a human verification. We can do it even after a day or the first CRAN release.

Good point. We can remove the examples IN ONE COMMIT and revert this commit easily later. We just need to keep the merged branch longer to preserver the commit (commits are squashed when merged to main). This is the fastest solution. Examples are just for us so we can address this later. So I suggest to remove examples now

**Comment by averissimo** [comment]
What exactly are the private examples here? I can't find any on `teal.data`

**Comment by chlebowa** [comment]
This?
> Examples for unexported function
default_cdisc_join_keys() in:
col_labels.Rd

**Comment by averissimo** [comment]
> Examples for unexported function
> default_cdisc_join_keys() in:
> col_labels.Rd

In `col_label.Rd` all the calls are from exported functions.

`default_cdisc_join_keys` is exported

**Comment by averissimo** [comment]
And the only `getFromNamespace` hit is when we import `lang2calls` (`R/zzz.R`)

**Comment by m7pr** [comment]
let's submit without the change in examples then haha
