### ISSUE TITLE
[Question]: Should we release `teal.data` again?

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.data#291]
Since we now have a solid flow for releasing a package on CRAN 
and we did provide a couple of small improvements (**and bug fixes!**) to `teal.data`,
should we quickly submit an updated patched version to CRAN? 

Imho a version update to patch (`x.y.z` - I mean `z`) should be enough.

The release can cover:
- feature request https://github.com/insightsengineering/teal.data/pull/290
- bug fix https://github.com/insightsengineering/teal.data/pull/289

**Comment by donyunardi** [comment]
I am fine with releasing teal.data again.
As discussed, we can prioritize the bug fix and release `0.4.1`.

**Comment by donyunardi** [comment]
I merged the fix and created Issue, 
https://github.com/insightsengineering/teal.data/issues/293

Let's release a patch.
