### ISSUE TITLE
Enable cdisc sdtm data

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.data#36]
<REDACTED>NEST/teal/pull/1114) cdisc_data() requires ADSL dataset. We should adapt this constraint to allow sdtm data as well. Are there other cdisc flavours we should be aware of (that may make a difference to how we implement it).

In order to support sdtm fully there are a few other changes needed:

- get_cdisc_keys() only works for AdAM

- default parent is ADSL throughout code base - maybe we need a get_cdisc_parent function which returns DM, ADSL or character(0) as appropriate

![image](https://user-images.githubusercontent.com/12943682/128368253-3fdc4f6a-5920-4af8-87bc-93472393a7c2.png)
- random_cdisc_data does not give sdtm

- updates to docs and agile-R about what we support (sample app? - although as we start having more and more of these we may need to change our approach...)

- downstream updates to tmc, teal.[osprey|goshawk], (tlg-catalog??) - are these likely to be used with sdtm, if so are default arguments sensible etc. - how much effort is it for users? depending on how these will be used might impact on how it is implemented. 

Also related to #1111 in terms of structure of cdisc class

FYI @anajens 

Provenance: 
```
Creator: burkoffn
```

**Comment by gogonzo** [comment]
Closing this as refactored teal.data is not limited to neither ADaM nor SDTM. Join keys can connect any datanames. For ADaM datasets we have `default_cdisc_join_keys`. I think that we misuse word CDISC in `teal`. We should have call this `default_adam_join_keys`, do you think so @lcd2yyz ? 
Besides this comment I'm closing issue as SDTM (like any other) is enabled

**Comment by lcd2yyz** [comment]
> We should have call this `default_adam_join_keys`, do you think so @lcd2yyz ?

Agree! 
Although I think we should eventually also create `default_sdtm_join_keys`, as SDTM is the other most important standard data models in CDISC. But would need consultation from DSG and SME before implementation.
