### ISSUE TITLE
Reproducible metadata attribute

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#76]
### Feature description

If TealDataset's metadata was an attribute of the data - then:
1. Would be reproducible - `attr(<dataset>, "metadata") <- <metadata call>`.
2. Would be easy to obtain `attr(<raw data>,  "metadata")`
3. Wouldn't be needed to specify this as a argument in FilteredData as attr will follow the (raw) data. Only one operation which removes attribute from data.frame is removing a columns - dplyr calls preserve attributes

```r
a <- data.frame(a = 1, b = 2)
attr(a, "metadata") <- "test"
a$c <- 3
attr(a, "metadata")
# "test"

a |>
  dplyr::filter(a == 0) |>
  dplyr::select(-c) |>
  dplyr::left_join(a, "a") |>
  attr("metadata")
# [1] "test"

a[1:2] |> attr("metadata")
# NULL
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by nikolas-burkoff** [comment]
I'm happy with this, we'll also need to make changes in internal connector packages of course

**Comment by kumamiao** [comment]
Sounds good, no strong preferences from me as long as app developers can 1) grab the metadata within a module 2) use the front page module to check the metadata

**Comment by gogonzo** [comment]
sounds like plan - metadata could be obtained in the module by:

```r
# in case of datasets <FilteredData>
attr(datasets$get_data(<dataname>), "metadata")

# in case of data <list of reactive data>
attr(data[[<dataname>]](), "metadata")
```

**Comment by gogonzo** [comment]
implemented with new teal_data
