### ISSUE TITLE
Remove primary keys field in Dataset and DatasetConnector

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.data#9]
Currently in `TealDataset` and `TealDatasetConnector` we have a keys (implemented before JoinKeys has been added) and join_keys fields:
- keys are set in the init and might be NULL
- join_keys are set through TealData which is really ineffective as following loop might be replaced by keys setting in Dataset$init
```r
      for (dat_name in names(self$get_items())) {
        if (length(join_keys$get(dat_name, dat_name)) == 0) {
          self$mutate_join_keys(dat_name, dat_name, get_keys(self$get_items(dat_name)))
        }
      }
```
- set_keys can simply be `set_join_keys(self$dataname(), self$dataname(), keys)`
- get_keys can simply `get_join_keys(self$dataname(), self$dataname())`

**Comment by donyunardi** [comment]
Need to reassess this again after some work in teal.data.

**Comment by gogonzo** [comment]
Not relevant anymore. New implementation of teal_data, teal_data_module and join_keys already on main
