### ISSUE TITLE
Update dataset_connector documentation

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.data#94]
https://github.com/insightsengineering/teal.data/blob/76c2e33f59057215569be210b54a10d28bc4f476/R/TealDatasetConnector_constructors.R#L25-L27

Line 27 should be:
> Can't be used simultaneously with `code`

**Comment by gogonzo** [comment]
Not relevant anymore. New implementation of teal_data, teal_data_module and join_keys already on main
