### ISSUE TITLE
review check() method 

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.data#97]
There are evidence of check method logic is buggy:

- https://github.com/insightsengineering/teal.data/issues/17
- https://github.com/insightsengineering/teal.data/issues/13

Need to find the root cause, review design, or refine action items.

**Comment by asbates** [comment]
I'd like to suggest considering a name change. `check` is not at all obvious. I think it should be something more like `check_code` or `check_dataset_code`.
